name: cooklang_dart
description: A cooklang parser in Dart
version: 1.0.0
homepage: https://github.com/aquilax/cooklang-dart

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  yaml: ^3.1.1
dependencies: {tuple: ^2.0.0}
